# Generated by Django 4.2.1 on 2024-08-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0004_uploadfiles2_group_uploadfiles2_time_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveConflictsTXT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_file', models.CharField(max_length=20)),
                ('file', models.FileField(null=True, upload_to='conflicts/txt', verbose_name='txt_files')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='uploadfiles2',
            name='status_file',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadfiles2',
            name='file',
            field=models.FileField(null=True, upload_to='conflicts/configs', verbose_name='config_file'),
        ),
    ]
