# Generated by Django 4.2.1 on 2024-08-04 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0005_saveconflictstxt_uploadfiles2_status_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveconflictstxt',
            name='file',
            field=models.FileField(null=True, upload_to='conflicts/txt/', verbose_name='txt_files'),
        ),
        migrations.AlterField(
            model_name='uploadfiles2',
            name='file',
            field=models.FileField(null=True, upload_to='conflicts/configs/', verbose_name='config_file'),
        ),
        migrations.AlterField(
            model_name='uploadfiles2',
            name='time_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
