# Generated by Django 4.2.1 on 2024-08-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0006_alter_saveconflictstxt_file_alter_uploadfiles2_file_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadFiles2',
            new_name='SaveConfigFiles',
        ),
    ]
