# Generated by Django 4.2.1 on 2024-08-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0008_rename_status_file_saveconfigfiles_destination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveconfigfiles',
            old_name='destination',
            new_name='source',
        ),
    ]
